return {
  {
    'nvim-treesitter/nvim-treesitter',
    branch = 'master',
    build = ':TSUpdate',
    main = 'nvim-treesitter.configs',
    opts = {
      ensure_installed = {
        'asm',
        'bash',
        'bibtex',
        'c',
        'cmake',
        'cpp',
        'css',
        'csv',
        'cuda',
        'dart',
        'diff',
        'dockerfile',
        'dot',
        'go',
        'html',
        'java',
        'javadoc',
        'javascript',
        'json',
        'kotlin',
        'latex',
        'llvm',
        'lua',
        'luadoc',
        'make',
        'markdown',
        'markdown_inline',
        'query',
        'matlab',
        'ocaml',
        'python',
        'rust',
        'sql',
        'typescript',
        'vim',
        'vimdoc',
        'xml',
        'yaml',
        'zig',
      },
      auto_install = true,
      highlight = {
        enable = true,
        -- Some languages depend on vim's regex highlighting system (such as Ruby) for indent rules.
        --  If you are experiencing weird indenting issues, add the language to
        --  the list of additional_vim_regex_highlighting and disabled languages for indent.
        additional_vim_regex_highlighting = { 'ruby' },
      },
      indent = { enable = false, disable = { 'ruby' } },
    },
  },
}
